// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerManagement.Persistence;

#nullable disable

namespace ServerManagement.Migrations
{
    [DbContext(typeof(ServerManagementContext))]
    partial class ServerManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServerManagement.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Calgary",
                            IsRunning = true,
                            Name = "Server1"
                        },
                        new
                        {
                            Id = 2,
                            City = "Halifax",
                            IsRunning = false,
                            Name = "Server2"
                        },
                        new
                        {
                            Id = 3,
                            City = "Toronto",
                            IsRunning = false,
                            Name = "Server3"
                        },
                        new
                        {
                            Id = 4,
                            City = "Ottawa",
                            IsRunning = false,
                            Name = "Server4"
                        },
                        new
                        {
                            Id = 5,
                            City = "Montreal",
                            IsRunning = false,
                            Name = "Server5"
                        },
                        new
                        {
                            Id = 6,
                            City = "Calgary",
                            IsRunning = true,
                            Name = "Server6"
                        },
                        new
                        {
                            Id = 7,
                            City = "Calgary",
                            IsRunning = true,
                            Name = "Server7"
                        },
                        new
                        {
                            Id = 8,
                            City = "Halifax",
                            IsRunning = false,
                            Name = "Server8"
                        },
                        new
                        {
                            Id = 9,
                            City = "Halifax",
                            IsRunning = false,
                            Name = "Server9"
                        },
                        new
                        {
                            Id = 10,
                            City = "Toronto",
                            IsRunning = true,
                            Name = "Server10"
                        },
                        new
                        {
                            Id = 11,
                            City = "Toronto",
                            IsRunning = false,
                            Name = "Server11"
                        },
                        new
                        {
                            Id = 12,
                            City = "Ottawa",
                            IsRunning = true,
                            Name = "Server12"
                        },
                        new
                        {
                            Id = 13,
                            City = "Ottawa",
                            IsRunning = false,
                            Name = "Server13"
                        },
                        new
                        {
                            Id = 14,
                            City = "Montreal",
                            IsRunning = false,
                            Name = "Server14"
                        },
                        new
                        {
                            Id = 15,
                            City = "Montreal",
                            IsRunning = false,
                            Name = "Server15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
